Update gb-hacks.json
correcting unique_id for all emulators due to error made using Find and Replace to update them:
Error: unique_ids were prefixed with "gb-hacks-hacks"
Correction: change prefix to "gb-hacks"